variables:
  REGISTRY: registry.ritc.jp/ricos/recode-gui

image: ${REGISTRY}/electron-cache:latest

stages:
    - deploy

pages:
    stage: deploy
    script:
        - npm install
        - make w
        - rm -fr ./dist/win-unpacked
        - mkdir -p ./public/
        - mv ./dist/* ./public/
        - cd ./public/
        - find -print > ../.tree
        - mv ../.tree .
    artifacts:
        paths:
            - public
        expire_in: 20min
